blog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('index/', views.IndexView.as_view(), name="index"),
    path('post_list/', views.PostListView.as_view(), name="post_list"),
    path('post_list/<int:pk>/', views.PostDetailView.as_view(), name="post_detail"),
    path('post_create/', views.PostCreateView.as_view(), name="post_create"),
    path('post_update/<int:pk>/', views.PostUpdateView.as_view(), name="post_update"),
    path('post_delete/<int:pk>/', views.PostDeleteView.as_view(), name="post_delete"),
#     path('post_draft/', views.DraftListView.as_view(), name="post_draft"),
#     path('post_list/<int:pk>/comment/', views.add_comment_to_post, name="comment_post"),
#     path('commment/<int:pk>/approve/', views.comment_approve, name="comment_approve"),
#     path('commment/<int:pk>/remove/', views.comment_remove, name="comment_remove"),
#     path('post_update/<int:pk>/publish/', views.post_publish, name="post_publish"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('app/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment = True)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs = {'pk': self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name = 'comments', on_delete = models.CASCADE)
    author = models.CharField(max_length = 200)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now)
    approved_comment = models.BooleanField(default = False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from blog.models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ('author', 'title', 'text')

        widgets = {
            'title' : forms.TextInput(attrs = {'class' : 'textinputclass'}),
            'text' : forms.Textarea(attrs = {'class' : 'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):
    
    class Meta():
        model = Comment
        fields = ('author', 'text')

        widgets = {
            'author' : forms.TextInput(attrs = {'class' : 'textinputclass'}),
            'text' : forms.Textarea(attrs = {'class' : 'editable medium-editor-textarea'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from blog.models import Post, Comment
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from blog.forms import PostForm, CommentForm
from django.utils import timezone

# Create your views here.
class IndexView(TemplateView):
    template_name = 'blog/about.html'

# about Post
class PostListView(ListView):
    context_object_name = 'posts'
    model = Post
    template_name = 'blog/post_list.html'

class PostDetailView(DetailView):
    context_object_name = 'post'
    model = Post
    template_name = 'blog/post_detail.html'

class PostCreateView(LoginRequiredMixin ,CreateView):
    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin, UpdateView):
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')

# class DraftListView(LoginRequiredMixin, ListView):
#     login_url = '/login/'
#     redirect_field_name = 'blog/post_list.html'
#     model = Post

#     def get_queryset(self):
#         return Post.objects.filter(published_date__isnull = True).order_by('created_date')

def post_publish(request, pk):
    post = get_object_or_404(Post, pk = pk)
    post.publish
    return redirect('post_detail',pk = pk)

# @login_required
# def add_comment_to_post(request, pk):
#     post = get_object_or_404(Post, pk = pk)

#     if request.method == "POST":
#         form = CommentForm(request.POST)

#         if form.is_valid():
#             comment = form.save(commit = False)
#             comment.post = post
#             comment.save()
#             return redirect('post_detail', pk = post.pk)
#     else:
#         form = CommentForm()

#     return render(request, 'blog/comment_form.html', {'form' : form})

# @login_required
# def comment_approve(request, pk):
#     comment = get_object_or_404(Comment, pk = pk)
#     comment.approve()
    
#     return redirect('post_detail', pk = comment.post.pk)

# @login_required
# def comment_remove(request, pk):
#     comment = get_object_or_404(Comment, pk = pk)
#     post_pk = comment.post.pk
#     comment.delete()

#     return redirect('post_detail', pk = post_pk)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block body %}
    <h1>Abhishek Soni</h1>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>Blog</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>

    <body>

        <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <a class="navbar-brand" href="#">Blog</a>
              </div>
              <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'blog:index' %}">Home</a></li>
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                <li><a href="{% url 'blog:post_create' %}">Post Create</a></li>
                <li><a href="{% url 'blog:post_list' %}">Post List</a></li>
              </ul>
            </div>
          </nav>
        
        <div class="content container">
          <div class="row">
            <div class="col-md-8">
              <div class="blog_posts">
                {% block body %}
  
                {% endblock %}
              </div>
            </div>
          </div>
        </div>

    </body>
</html>

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block body %}
    <h1>{{ post.text }}</h1>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block body %}
    {% for post in posts %}
        <a href="{{ post.id }}"><h1>{{post}}</h1></a>
    {% endfor %}
{% endblock %}

templates/blog/about.html
{% extends 'blog/base.html' %}

{% block body %}
    <h1>Abhishek Soni</h1>
{% endblock %}

templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>Blog</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>

    <body>

        <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <a class="navbar-brand" href="#">Blog</a>
              </div>
              <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'blog:index' %}">Home</a></li>
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                <li><a href="{% url 'blog:post_create' %}">Post Create</a></li>
                <li><a href="{% url 'blog:post_list' %}">Post List</a></li>
              </ul>
            </div>
          </nav>
        
        <div class="content container">
          <div class="row">
            <div class="col-md-8">
              <div class="blog_posts">
                {% block body %}
  
                {% endblock %}
              </div>
            </div>
          </div>
        </div>

    </body>
</html>